//! Compaction: rolling context summary for short-context models.
//!
//! When the derived message history exceeds a threshold (configurable as a
//! fraction of context_window), older turns are summarized into a single
//! system message. The critical design invariant:
//!
//! **The summary request uses an independent context.**
//!
//! The summary LLM call does NOT include the conversation being summarized.
//! It receives only: a system instruction + the raw text of the turns to
//! compress. This prevents the summary from bloating the very context it's
//! trying to save, and keeps the summary focused.
//!
//! Flow:
//! 1. Agent loop detects derived messages exceed threshold
//! 2. Takes the oldest N turns (keeping `keep_recent_turns` recent)
//! 3. Renders those turns as plain text
//! 4. Sends a single LLM call: "Summarize this conversation" + the text
//! 5. Replaces those turns with one compact summary message
//! 6. The session log records a Compaction event (trajectory-only)

use crate::types::*;
use crate::llm::{LlmClient, LlmRequest, StreamEvent};

/// The result of a compaction pass.
pub struct CompactionResult {
    /// The summary text generated by the LLM.
    pub summary: String,
    /// Number of turns that were compacted.
    pub turns_compacted: usize,
}

/// Check if compaction is needed based on message count and threshold.
///
/// `message_count` = number of derived messages
/// `context_window` = model's context window size (in tokens, approximated by char count / 4)
/// `threshold` = fraction of context window that triggers compaction (e.g. 0.7)
pub fn needs_compaction(message_count: usize, context_window: usize, threshold: f32) -> bool {
    if context_window == 0 {
        return false;
    }
    // Rough estimate: 1 message ≈ 200 tokens average. Trigger when estimated
    // token usage exceeds threshold * context_window.
    let estimated_tokens = message_count * 200;
    let trigger_at = (context_window as f32 * threshold) as usize;
    estimated_tokens > trigger_at
}

/// Render a slice of messages into plain text for the summary LLM call.
/// This is the "independent context" — just the raw conversation text.
fn render_messages_for_summary(messages: &[Message]) -> String {
    let mut out = String::new();
    for msg in messages {
        match msg {
            Message::User { content } => {
                out.push_str(&format!("[User]: {content}\n"));
            }
            Message::Assistant { content, tool_calls } => {
                if !content.is_empty() {
                    out.push_str(&format!("[Assistant]: {content}\n"));
                }
                for tc in tool_calls {
                    out.push_str(&format!("[Tool Call]: {}({})\n", tc.name, tc.arguments));
                }
            }
            Message::Tool { call_id, content, is_error } => {
                let tag = if *is_error { "ERROR" } else { "RESULT" };
                out.push_str(&format!("[Tool {tag} {call_id}]: {content}\n"));
            }
        }
    }
    out
}

/// Perform a compaction pass: summarize older messages into a single summary.
///
/// Uses an INDEPENDENT LLM call — the summary request contains only the
/// system instruction + the raw text of the messages to compress, NOT the
/// full conversation history.
///
/// Returns `None` if there aren't enough messages to compact.
pub async fn compact(
    llm: &LlmClient,
    model: &str,
    temperature: f32,
    messages: &[Message],
    keep_recent: usize,
) -> Option<CompactionResult> {
    // Need at least keep_recent + 2 messages to make compaction worthwhile.
    if messages.len() <= keep_recent + 2 {
        return None;
    }

    let split_point = messages.len().saturating_sub(keep_recent);
    let to_compact = &messages[..split_point];

    if to_compact.is_empty() {
        return None;
    }

    let conversation_text = render_messages_for_summary(to_compact);
    let turns_compacted = to_compact.len();

    log::info!(
        "Compacting {} messages (keeping {} recent), text size = {} chars",
        turns_compacted,
        keep_recent,
        conversation_text.len()
    );

    // Independent context: just the instruction + raw conversation text.
    let summary_instruction = "You are a conversation summarizer. Summarize the following conversation \
        into a concise summary that preserves: key facts discovered, decisions made, tool results \
        obtained, and any pending tasks. Be brief but complete. Do not add information not present \
        in the conversation.";

    let request = LlmRequest {
        model: model.to_string(),
        system: String::new(),
        messages: vec![
            Message::User {
                content: format!("{summary_instruction}\n\n--- CONVERSATION TO SUMMARIZE ---\n\n{conversation_text}"),
            },
        ],
        tools: vec![],
        max_tokens: 1024,
        temperature, // low temperature for faithful summary
        think: false, // summarization doesn't need reasoning
    };

    let (stream_tx, mut stream_rx) = tokio::sync::mpsc::channel(64);
    let llm_clone = llm.clone();
    let handle = tokio::spawn(async move {
        llm_clone.stream(request, stream_tx).await
    });

    let mut summary = String::new();
    while let Some(event) = stream_rx.recv().await {
        match event {
            StreamEvent::Delta(text) => summary.push_str(&text),
            StreamEvent::ThinkDelta(_) => {
                // Thinking content not needed for summarization — discard.
            }
            StreamEvent::Done { content, .. } => {
                if !content.is_empty() {
                    summary = content;
                }
            }
            StreamEvent::ToolCall(_) => {}
            StreamEvent::Error(e) => {
                log::warn!("Compaction LLM call failed: {e}");
                let _ = handle.await;
                return None;
            }
        }
    }
    let _ = handle.await;

    if summary.is_empty() {
        log::warn!("Compaction produced empty summary");
        return None;
    }

    log::info!("Compaction complete: {} chars summary", summary.len());
    Some(CompactionResult {
        summary,
        turns_compacted,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_needs_compaction() {
        // 0 context window = no compaction
        assert!(!needs_compaction(100, 0, 0.7));
        // Small message count, large window = no
        assert!(!needs_compaction(5, 8192, 0.7));
        // Large message count, small window = yes
        assert!(needs_compaction(100, 8192, 0.7));
    }

    #[test]
    fn test_render_messages() {
        let messages = vec![
            Message::User { content: "check interface".into() },
            Message::Assistant { content: "I'll check now.".into(), tool_calls: vec![] },
            Message::Tool { call_id: "tc1".into(), content: "eth0 is up".into(), is_error: false },
        ];
        let text = render_messages_for_summary(&messages);
        assert!(text.contains("[User]: check interface"));
        assert!(text.contains("[Assistant]: I'll check now."));
        assert!(text.contains("[Tool RESULT tc1]: eth0 is up"));
    }

    #[test]
    fn test_render_error_tool() {
        let messages = vec![
            Message::Tool { call_id: "tc1".into(), content: "command not found".into(), is_error: true },
        ];
        let text = render_messages_for_summary(&messages);
        assert!(text.contains("[Tool ERROR tc1]: command not found"));
    }
}
